PACKAGE_NAME="x-fan40"
PACKAGE_VERSION="1.0.2"
BUILT_MODULE_NAME[0]="x-fan40-aux-thermal"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build module"
CLEAN="make clean"
